### ISSUE TITLE
CRUD for tasks

### ISSUE THREAD

**Issue by OlegZapara** [ikeepcalm/queue-up-now#4]
### *GET* Get tasks
**/tasks** returns an array or tasks, including task ID:
```
[
  {
    id,
    dueDate,
    dueTime,
    taskName,
    url
  },
  {
    ...
  }
]
```
### *GET* Get task  by ID
**/tasks/:id** returns task with specified ID
```
{
  id,
  dueDate,
  dueTime,
  taskName,
  url
}
```

### *PUT* Update task
**/tasks** takes task as body parameter
```
{
  id,
  dueDate,
  dueTime,
  taskName,
  url
}
```
And returns 200(OK) or 204(NO CONTENT) with no response body
### *POST* Create task
**/tasks** takes task without ID as body parameter
```
{
  dueDate,
  dueTime,
  taskName,
  url
}
```
Returns 201(CREATED) with link to created resource
### *DELETE* Delete task
**/tasks/:id** takes single ID parameter to delete task
Returns 200(OK) or 204(NO CONTENT) with no response body

### Note

> All endpoints should contain API key and chatID in headers

**Comment by ikeepcalm** [comment]
Seems like Tasks controller was updated according to these CRUD requirements, including path parameters. 

Feel free to test it and tell if something is odd. Screenshot from the Swagger Docs attached below:

![image](https://github.com/ikeepcalm/queue-up-now/assets/97694826/0a532c91-ae5e-4809-9520-cace31a78055)
